# Generated by Django 4.2.13 on 2024-05-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "email",
                    models.EmailField(
                        max_length=500, unique=True, verbose_name="email"
                    ),
                ),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "end_user"), (2, "librarian"), (3, "admin")],
                        default=1,
                        verbose_name="account_type",
                    ),
                ),
                (
                    "phone_num",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="phone_number"
                    ),
                ),
                (
                    "f_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="first_name"
                    ),
                ),
                (
                    "l_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="last_name"
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(auto_now_add=True, verbose_name="date joined"),
                ),
                (
                    "last_login",
                    models.DateTimeField(auto_now=True, verbose_name="last login"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
